# Visa EPIN Settlement Service Configuration
# Configuration commune pour tous les profils

server:
  port: 8080
  servlet:
    context-path: /cardexis-settlement
  tomcat:
    max-http-form-post-size: 500MB
    max-swallow-size: 500MB
    threads:
      max: 50
      min-spare: 10
    connection-timeout: 300000
    max-connections: 8192
    accept-count: 100
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  application:
    name: cardexis-settlement-service
  
  profiles:
    active: development
  
  # Add servlet multipart configuration here
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 0
      enabled: true
  
  # JPA Configuration commune
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: false
  
  # Data Auditing
  data:
    jpa:
      repositories:
        enabled: true
  
  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
  
  # Async Processing
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100
        keep-alive: 60s
      thread-name-prefix: epin-processing-
    scheduling:
      pool:
        size: 5
      thread-name-prefix: epin-scheduler-

# JWT Configuration (identique à API-1)
jwt:
  private-key: classpath:jwt/app.key
  public-key: classpath:jwt/app.pub
  access-token-ttl: 5m
  refresh-token-ttl: 1d

# Logging Configuration commune
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: "Cardexis Settlement Service API"
    description: "REST API for processing Visa EPIN settlement files (VSS-110)"
    version: "1.0.0"
    contact:
      name: "EL.AHGOUNE"
      email: "support@cardexis.com"
    license:
      name: "Proprietary"

# Application-Specific Configuration
visa:
  epin:
    processing:
      # File Processing Settings
      max-file-size: 100MB
      supported-formats:
        - VSS_110
      
      # Retry Configuration
      max-retries: 3
      retry-delay: 5000
      
      # Validation Settings
      strict-validation: true
      skip-invalid-records: false
      
      # Performance Settings
      batch-size: 1000
      parallel-processing: true
      max-concurrent-jobs: 10
      
      # Cleanup Settings
      cleanup:
        enabled: true
        retention-days: 90
        schedule: "0 2 * * *"  # Daily at 2 AM
    
    # File Format Specifications
    formats:
      vss110:
        record-identifier: "V2110"
        expected-length: 168
        transaction-code: "46"
        report-group: "V"
        report-subgroup: "2"
        report-ids:
          - "110"  # Detailed records
          - "111"  # Summary records
        amount-types:
          detailed: ["I", "F", "C", "T"]  # VSS-110 types
          summary: [" ", "T"]             # VSS-111 types
        business-modes:
          - "1"  # Acquirer
          - "2"  # Issuer
          - "3"  # Other
          - "9"  # Total
        validation:
          strict-mode: true
          skip-invalid-records: false
          max-line-length: 168
          min-line-length: 155
        parsing:
          default-currency: "USD"
          implied-decimals: 2
          date-format: "CCYYDDD"
          amount-padding: "zero"
    
    # Client Configuration
    clients:
      default:
        max-concurrent-uploads: 5
        rate-limit: 100  # requests per hour
        allowed-file-types:
          - "txt"
          - "dat"

# VSS Field Mapping Configuration
# Based on ReadingReports.txt specifications
vss:
  field-mapping:
    # Report 110 - Settlement Summary
    report110:
      settlement-currency:
        position: 24
        direction: LEFT_TO_RIGHT
        max-length: 3
      count:
        position: 52
        direction: RIGHT_TO_LEFT
        max-length: 15
      credit-amount:
        position: 78
        direction: RIGHT_TO_LEFT
        max-length: 20
      debit-amount:
        position: 104
        direction: RIGHT_TO_LEFT
        max-length: 20
      total-amount:
        position: 132
        direction: RIGHT_TO_LEFT
        max-length: 20

    # Report 120 - Interchange Value
    report120:
      settlement-currency:
        position: 24
        direction: LEFT_TO_RIGHT
        max-length: 3
      clearing-currency:
        position: 24
        direction: LEFT_TO_RIGHT
        max-length: 3
      table-id:
        position: 52
        direction: RIGHT_TO_LEFT
        max-length: 10
      count:
        position: 67
        direction: RIGHT_TO_LEFT
        max-length: 15
      clearing-amount:
        position: 90
        direction: RIGHT_TO_LEFT
        max-length: 20
      interchange-credits:
        position: 104
        direction: RIGHT_TO_LEFT
        max-length: 20
      interchange-debits:
        position: 130
        direction: RIGHT_TO_LEFT
        max-length: 20

    # Report 130 - Reimbursement Fees
    report130:
      settlement-currency:
        position: 24
        direction: LEFT_TO_RIGHT
        max-length: 3
      count:
        position: 62
        direction: RIGHT_TO_LEFT
        max-length: 15
      interchange-amount:
        position: 87
        direction: RIGHT_TO_LEFT
        max-length: 20
      reimbursement-fee-credits:
        position: 110
        direction: RIGHT_TO_LEFT
        max-length: 20
      reimbursement-fee-debits:
        position: 132
        direction: RIGHT_TO_LEFT
        max-length: 20

    # Report 140 - Visa Charges
    report140:
      settlement-currency:
        position: 24
        direction: LEFT_TO_RIGHT
        max-length: 3
      count:
        position: 67
        direction: RIGHT_TO_LEFT
        max-length: 15
      interchange-amount:
        position: 90
        direction: RIGHT_TO_LEFT
        max-length: 20
      visa-charges-credits:
        position: 111
        direction: RIGHT_TO_LEFT
        max-length: 20
      visa-charges-debits:
        position: 132
        direction: RIGHT_TO_LEFT
        max-length: 20

    # Report 900 - Summary Reconciliation
    report900:
      clearing-currency:
        position: 22
        direction: LEFT_TO_RIGHT
        max-length: 3
      count:
        position: 67
        direction: RIGHT_TO_LEFT
        max-length: 15
      clearing-amount:
        position: 89
        direction: RIGHT_TO_LEFT
        max-length: 20
      total-count:
        position: 106
        direction: RIGHT_TO_LEFT
        max-length: 15
      total-clearing-amount:
        position: 131
        direction: RIGHT_TO_LEFT
        max-length: 20

# Datasource Configuration
datasource:
  hikari:
    maximum-pool-size: 20
    minimum-idle: 5
    connection-timeout: 60000
    validation-timeout: 5000
    idle-timeout: 600000
    max-lifetime: 1800000
    leak-detection-threshold: 60000

# JVM optimization for large files (add to startup)
# -Xmx2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200