spring:
  datasource:
    url: jdbc:postgresql://ms-bill-dev.cngg0ec2ij77.eu-west-3.rds.amazonaws.com:5432/MS_BILLING
    username: msbill_dev
    password: uqvhLdVb0OeGMQwXjkQp
    driver-class-name: org.postgresql.Driver
    jpa:
     hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: MS-BILLING
  jpa:
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587 # You can change it to 25, 465, or 587 if needed
    username: elhassane.ahgoune@gmail.com
    password: oecv gawg snrt ozqq
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true # Optional, for debugging email issues
  data:
    redis:
      repositories:
        enabled: false

springdoc:
  swagger-ui:
    use-root-path: true

jwt:
  private-key: classpath:jwt/app.key
  public-key: classpath:jwt/app.pub
  access-token-ttl: 5m
  refresh-token-ttl: 1d

otp:
  email-verification:
    cache-prefix: otp:email-verification:%s
    ttl: 5m
    length: 6

